import { ThemeMode } from '../types';

export const themeRegistry: Record<ThemeMode, Record<string, string>> = {
  light: {
    '--background': '#ffffff',
    '--background-alt': '#f8fafc',
    '--surface': '#ffffff',
    '--surface-elevated': '#ffffff',
    '--text-primary': '#0f172a',
    '--text-secondary': '#475569',
    '--text-inverse': '#ffffff',
    '--border': '#e2e8f0',
    '--border-strong': '#cbd5e1',
    '--primary': '#0f172a',
    '--primary-foreground': '#ffffff',
    '--accent': '#2563eb', // cyan/teal could be used, fallback to blue for now as requested
    '--accent-foreground': '#ffffff',
    '--success': '#22c55e',
    '--warning': '#eab308',
    '--error': '#ef4444',
    '--shadow': 'rgba(0, 0, 0, 0.05)',
    '--overlay': 'rgba(0, 0, 0, 0.5)',
  },
  dark: {
    '--background': '#020617',
    '--background-alt': '#0f172a',
    '--surface': '#0f172a',
    '--surface-elevated': '#1e293b',
    '--text-primary': '#f8fafc',
    '--text-secondary': '#94a3b8',
    '--text-inverse': '#020617',
    '--border': '#1e293b',
    '--border-strong': '#334155',
    '--primary': '#ffffff',
    '--primary-foreground': '#0f172a',
    '--accent': '#3b82f6',
    '--accent-foreground': '#ffffff',
    '--success': '#22c55e',
    '--warning': '#eab308',
    '--error': '#ef4444',
    '--shadow': 'rgba(0, 0, 0, 0.2)',
    '--overlay': 'rgba(0, 0, 0, 0.7)',
  },
  corporate: {
    '--background': '#0f172a',
    '--background-alt': '#1e293b',
    '--surface': '#1e293b',
    '--surface-elevated': '#334155',
    '--text-primary': '#ffffff',
    '--text-secondary': '#cbd5e1',
    '--text-inverse': '#0f172a',
    '--border': '#334155',
    '--border-strong': '#475569',
    '--primary': '#3b82f6',
    '--primary-foreground': '#ffffff',
    '--accent': '#0ea5e9', // Teal/Cyan accent for Al-Mithali
    '--accent-foreground': '#ffffff',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--error': '#ef4444',
    '--shadow': 'rgba(0, 0, 0, 0.25)',
    '--overlay': 'rgba(15, 23, 42, 0.8)',
  }
};
